In [2]:
#Inspecting about Numpy and Pandas
import numpy as np

In [7]:
arr_0d = np.array(2)
print(arr_0d)
print(type(arr_0d))

2
<class 'numpy.ndarray'>


In [4]:
arr_1d = np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [8]:
#dimension comparing
print(arr_0d.shape)
print(arr_1d.shape)
print(arr_2d.shape)

()
(3,)
(2, 3)


In [9]:
print(np.zeros(3))

[0. 0. 0.]


In [10]:
print(np.ones(3))

[1. 1. 1.]


In [11]:
print(np.arange(3))

[0 1 2]


In [12]:
print(np.arange(1,4,1))

[1 2 3]


In [13]:
print(np.linspace(3,4))

[3.         3.02040816 3.04081633 3.06122449 3.08163265 3.10204082
 3.12244898 3.14285714 3.16326531 3.18367347 3.20408163 3.2244898
 3.24489796 3.26530612 3.28571429 3.30612245 3.32653061 3.34693878
 3.36734694 3.3877551  3.40816327 3.42857143 3.44897959 3.46938776
 3.48979592 3.51020408 3.53061224 3.55102041 3.57142857 3.59183673
 3.6122449  3.63265306 3.65306122 3.67346939 3.69387755 3.71428571
 3.73469388 3.75510204 3.7755102  3.79591837 3.81632653 3.83673469
 3.85714286 3.87755102 3.89795918 3.91836735 3.93877551 3.95918367
 3.97959184 4.        ]


In [14]:
print(np.linspace(1,2,10))

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [15]:
#slicing an array
arr_1d = np.array([1,2,3])
print(arr_1d[0])
print(arr_1d[1])

1
2


In [17]:
arr_x = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(arr_x[0,1])
print(arr_x[1,:])
print(arr_x[:,0])
print(arr_x[2:,2:])
print(arr_x[:,:-1])
print(arr_x > 5)
print(arr_x[arr_x > 5])

2
[5 6 7 8]
[ 1  5  9 13]
[[11 12]
 [15 16]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15 16]


In [20]:
#math operations with numpy
arr_1d_a = np.array([1,2,3])
arr_1d_b = np.array([4,5,6])


arr_1d_a + 10

array([11, 12, 13])