In [1]:
import numpy as np
arr1 = np.array([10,20,30,40,50])
print(arr1)
print(type(arr1))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
#question 3 : A supermarket records the number of apples sold over 7 days:
sales = np.array([23,45,12,67,34,89,21])
print(f"First Day Sales : {sales[0]}")
print(f"Last Day Sales : {sales[-1]}")

First Day Sales : 23
Last Day Sales : 21


In [8]:
#question 4 : Expected Output
arr4 = np.array([1,2.5,3,4])
print(arr4.dtype)

float64


In [11]:
#question 5 : What will happen?
arr5 = np.array([1,2,3,4,"hello"], )
print(arr5)
print(arr5.dtype)

['1' '2' '3' '4' 'hello']
<U21


In [12]:
#question 6 : School store student information
student = np.array([101,"John",3.05])
print(student)
print(student.dtype)

['101' 'John' '3.05']
<U32


In [13]:
#question 7 : Write a line of code to create 10 equally spaced values between: 0 and 100
arr7 = np.linspace(0,100,10)
print(arr7)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [14]:
#question 8 : Predict the output
x = np.linspace(1,5,5)
print(x)

[1. 2. 3. 4. 5.]


In [15]:
#question 9 : A scientist wants to test temperatures between 20°C and 80°C using 7 equally spaced samples.
temptest = np.linspace(20,80,7)
print(temptest)

[20. 30. 40. 50. 60. 70. 80.]


In [18]:
#question 10 : Given 
arr10 = np.array([5, 10, 15, 20, 25, 30])
#write code to acess first, last element and middle 3 element
print(arr10[0])
print(arr10[-1])
print(arr10[1:4])

5
30
[10 15 20]


In [20]:
#question 11 : Given:
arr11 = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
#access 50
print(arr11[1][1])
#entire second row
print(arr11[1,:])
#entire first column
print(arr11[:,0])

50
[40 50 60]
[10 40 70]


In [21]:
#question 12 : predict output
arr = np.array([2,4,6,8,10])
print(arr[1:4])

[4 6 8]


In [22]:
#question 13 : covert array to float
arr13 = np.array([1,2,3,4,5])
convert = arr.astype(float)
print(arr13)

[1 2 3 4 5]


In [23]:
#question 14 : predict output ??????
arr14 = np.array([1.9,2.7,3.1])
new_arr14 = arr.astype(int)
print(new_arr14)

[ 2  4  6  8 10]


In [27]:
#question 15 : A hospital imported patient ages from a CSV file:
raw = ["25", "31", "42", "55"]
convert = np.array(raw).astype(int)
#convert = np.array(raw, dtype = int)
print(convert)

[25 31 42 55]


In [32]:
#question 19 : find sum mean maximum value of the given array
scores = np.array([78, 85, 91, 66, 88])
print(f"Summation of the score {np.sum(scores)}")
print(f"Mean of the score {np.mean(scores)}")
print(f"Maximum value of the score {np.max(scores)}")

Summation of the score 408
Mean of the score 81.6
Maximum value of the score 91


In [ ]:
#question 20 : A company tracks employee monthly salaries
salary = [25000, 30000, 28000, 35000]
#Management increases salaries by 8%

In [33]:
#question 21 : given and create new array containing only element greater than 15
arr21 = np.array([5,10,15,20,25,30,35])
arr21_processed = arr21[arr21 > 15]
print(arr21_processed)

[20 25 30 35]


In [37]:
#question 22 : predict output
arr22 = np.array([10,20,30,40,50])
print(arr22[:3]*2)

[20 40 60]


In [48]:
#question 23 : A weather station records temperature
temp = [30, 32, 35, 29, 31, 34, 36]
converttemp = np.array(temp)
d3_d6 = converttemp[2:6]
#Get the temperature day3 to day 6
print(d3_d6)
#Convert from celcius to fahrenheit (all)
faren = (converttemp * 9/5) + 32
print(faren)

[35 29 31 34]
[86.  89.6 95.  84.2 87.8 93.2 96.8]


In [49]:
#question 24 : Predict multi data-type trap ?????
arr24 = np.array([True, 1, 2.5])

print(arr)
print(arr.dtype)

[ 2  4  6  8 10]
int64


In [50]:
#question 25 : slicing trap ????
arr25 = np.array([10,20,30,40,50,60])

print(arr25[-4:-1])

[30 40 50]


In [54]:
#question 27 : Scenario based data cleaning : A dataset arrives like this
#convert data type properly, add 5 to all values, find average
data = np.array(["12", "15", "18", "20", "22"])
converter = data.astype(int) + 5
print(converter)
print(f"AvG value is {np.mean(converter)}")

[17 20 23 25 27]
AvG value is 22.4


In [60]:
#question 28 : 2d slicing challenge : given
matrix = np.array([
    [5,10,15,20],
    [25,30,35,40],
    [45,50,55,60]
])
#get second row only, third column only and submatrix
print(f"Second Row only : {matrix[1,:]}")
print(f"Third Column only : {matrix[:,2]}")

subrow = [0,1]
subcol = [1,2]

submatrix = matrix[np.ix_(subrow,subcol)]
print(submatrix)

Second Row only : [25 30 35 40]
Third Column only : [15 35 55]
[[10 15]
 [30 35]]


In [63]:
#question 29 : Scenario Based Analysis
steps = np.array([4200, 5800, 6100, 10000, 3000, 8200, 7600])
#calculate average steps
print(f"Average Steps : {np.mean(steps)}")
#find highest steps
print(f"Highest Steps : {np.max(steps)}")
#find days with more than 6000 steps
days = np.where(steps > 6000)[0] + 1
print(days)
#Increase every value by 500
steps_in5 = steps + 500
print(steps_in5)

Average Steps : 6414.285714285715
Highest Steps : 10000
[3 4 6 7]
[ 4700  6300  6600 10500  3500  8700  8100]


In [73]:
#question 30 : Mini Case study (Hard)
scores = np.array([
    [70, 80, 90],
    [88, 76, 95],
    [60, 75, 85]
])
# each row = student, each column = subject
# find average score of each student
print(f"AVG Student : {np.mean(scores, axis = 1)}")
# find average score of each subject
print(f"AVG Subject : {np.mean(scores, axis = 0)}")
# Highest score in the whole matrix
print(f"Max Score : {np.max(scores)}")
# Extract all scores greater than 80
print(f"Extract : {scores[scores > 80]}")

AVG Student : [80.         86.33333333 73.33333333]
AVG Subject : [72.66666667 77.         90.        ]
Max Score : 95
Extract : [90 88 95 85]
