In [2]:
import numpy as np

In [6]:
arr_0d = np.array(2)
print(arr_0d)
print(type(arr_0d))

2
<class 'numpy.ndarray'>


In [7]:
#considered as vector
arr_1d = np.array([1,2,3])
print(arr_1d)
print(type(arr_1d))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
#considered as matrix
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(type(arr_2d))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [18]:
arr_mix = np.array([["ikkyu",1,3.14],[2,3,"Pong"]], dtype = object)
print(arr_mix)
print(type(arr_mix))
print(arr_mix[0][1]) #accessing into values
print(type(arr_mix[1][2]))

[['ikkyu' 1 3.14]
 [2 3 'Pong']]
<class 'numpy.ndarray'>
1
<class 'str'>


In [23]:
print(np.zeros(4))
print(np.ones(3))
print(np.arange(3))
print(np.arange(1,4,1))
lin = np.linspace(3,4,10)
print(lin)
print(type(lin))

[0. 0. 0. 0.]
[1. 1. 1.]
[0 1 2]
[1 2 3]
[3.         3.11111111 3.22222222 3.33333333 3.44444444 3.55555556
 3.66666667 3.77777778 3.88888889 4.        ]
<class 'numpy.ndarray'>


In [25]:
sli1 = np.array([[1,2,3],
                [4,5,6]])
print(sli1[0][1])
print(sli1[0,1])

2
2


In [33]:
sli2 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10],
                 [11,12,13,14,15]])
print(sli2[2,3])
print(sli2[1,:]) #row index 1 all
print(sli2[:,0]) #column index 0 all
# start sel. data from row2 col2 so on
print(sli2[2:,2:])
#select except last 3 columns
print(sli2[:,:-3])
#condition compare
print(sli2 > 5)
#query value within condition
print(sli2[sli2 > 5])

14
[ 6  7  8  9 10]
[ 1  6 11]
[[13 14 15]]
[[ 1  2]
 [ 6  7]
 [11 12]]
[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 6  7  8  9 10 11 12 13 14 15]


In [35]:
print(sli2[np.where(sli2 > 5)])

[ 6  7  8  9 10 11 12 13 14 15]


In [42]:
print(type(sli2))
print(sli2.dtype)
convert = sli2.astype(float)
print(convert)
print(type(convert))
print(convert.dtype)

<class 'numpy.ndarray'>
int64
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
<class 'numpy.ndarray'>
float64


In [43]:
x = [3,4,5]
y = [5,12,13]
z = []

for i in range (len(x)):
    z.append(x[i] + y[i])
print(z)

[8, 16, 18]


In [46]:
marr1 = np.array([1,2,3])
marr2 = np.array([4,5,6])
print(marr1 + marr2)
print(marr1 + 10)

[5 7 9]
[11 12 13]


In [48]:
print(marr2 - marr1)
print(np.subtract(marr2, marr1))

[3 3 3]
[3 3 3]


In [49]:
print(marr1 * marr2)

[ 4 10 18]


In [51]:
print(marr1 / marr2)
print(marr2 / marr1)
print(marr2 / 2)

[0.25 0.4  0.5 ]
[4.  2.5 2. ]
[2.  2.5 3. ]


In [52]:
print(marr1 **2)

[1 4 9]


In [53]:
print(marr1 % 2)

[1 0 1]
